import type { Endpoint } from "@/lib/endpoints/types";

const now = Date.now();
const minutesAgo = (n: number) => new Date(now - n * 60_000).toISOString();

// Includes every agent referenced in lib/cases/mock-data.ts (so endpoint
// counts and the case correlation view stay consistent), plus a few quiet
// endpoints with no alert history — real fleets are mostly quiet.
export const mockEndpoints: Endpoint[] = [
  {
    id: "ep_004",
    agent_id: "004",
    hostname: "WORKSTATION-FINANCE-02",
    customer_id: "cust_acme_01",
    customer_name: "Acme Bank - Victoria Island",
    os: "Windows 11",
    status: "isolated",
    last_seen: minutesAgo(4),
  },
  {
    id: "ep_011",
    agent_id: "011",
    hostname: "EDGE-GATEWAY-01",
    customer_id: "cust_acme_01",
    customer_name: "Acme Bank - Victoria Island",
    os: "Ubuntu 22.04",
    status: "online",
    last_seen: minutesAgo(1),
  },
  {
    id: "ep_007",
    agent_id: "007",
    hostname: "WORKSTATION-OPS-19",
    customer_id: "cust_acme_01",
    customer_name: "Acme Bank - Victoria Island",
    os: "Windows 11",
    status: "online",
    last_seen: minutesAgo(2),
  },
  {
    id: "ep_acme_04",
    agent_id: "acme-04",
    hostname: "WORKSTATION-FINANCE-01",
    customer_id: "cust_acme_01",
    customer_name: "Acme Bank - Victoria Island",
    os: "Windows 11",
    status: "online",
    last_seen: minutesAgo(3),
  },
  {
    id: "ep_acme_05",
    agent_id: "acme-05",
    hostname: "WORKSTATION-OPS-05",
    customer_id: "cust_acme_01",
    customer_name: "Acme Bank - Victoria Island",
    os: "Windows 10",
    status: "offline",
    last_seen: minutesAgo(612),
  },
  {
    id: "ep_022",
    agent_id: "022",
    hostname: "FILESRV-LAGOS-01",
    customer_id: "cust_globex_02",
    customer_name: "Globex Logistics",
    os: "Windows Server 2022",
    status: "isolated",
    last_seen: minutesAgo(9),
  },
  {
    id: "ep_018",
    agent_id: "018",
    hostname: "LAPTOP-SALES-14",
    customer_id: "cust_globex_02",
    customer_name: "Globex Logistics",
    os: "macOS 15",
    status: "online",
    last_seen: minutesAgo(5),
  },
  {
    id: "ep_globex_03",
    agent_id: "globex-03",
    hostname: "FILESRV-LAGOS-02",
    customer_id: "cust_globex_02",
    customer_name: "Globex Logistics",
    os: "Windows Server 2022",
    status: "online",
    last_seen: minutesAgo(1),
  },
  {
    id: "ep_033",
    agent_id: "033",
    hostname: "WORKSTATION-LAB-07",
    customer_id: "cust_umbrella_03",
    customer_name: "Umbrella Pharma NG",
    os: "Windows 11",
    status: "online",
    last_seen: minutesAgo(2),
  },
  {
    id: "ep_041",
    agent_id: "041",
    hostname: "WORKSTATION-HR-03",
    customer_id: "cust_umbrella_03",
    customer_name: "Umbrella Pharma NG",
    os: "Windows 11",
    status: "online",
    last_seen: minutesAgo(6),
  },
  {
    id: "ep_umbrella_03",
    agent_id: "umbrella-03",
    hostname: "WORKSTATION-LAB-03",
    customer_id: "cust_umbrella_03",
    customer_name: "Umbrella Pharma NG",
    os: "Windows 10",
    status: "online",
    last_seen: minutesAgo(4),
  },
];
